/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "i2c_lcd.h"
#include "string.h"
int main(void)
{
	int ret, count;
	char str[80];
	SystemInit();
	ret = Lcd_Init();
	if(ret)
	{
//		Lcd_Puts(LCD_LINE1, "M.S.DHONI 07");
		for(count = 1; count < 100; count++)
		{
			sprintf(str, "TEJAS", count);
			DelayMs(2000);
			Lcd_Puts(LCD_LINE1, str);
			DelayMs(500);
		}
	}
	return 0;
}

