/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "timer.h"
#include "i2c_lcd.h"
#include "i2c.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void) {

	SystemInit();
	Timer_Init(1000);
	char str1[32]="HELLO DESD!";
	char str2[32];
	int ret;
	ret=Lcd_Init();

	while(1){
		sprintf(str2,"Count=%d",count);
		Lcd_Puts(LCD_LINE1,str1);
		if(ret)
		{
		Lcd_Puts(LCD_LINE2,str2);
			}
	}
	return 0;
}




