/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "accel.h"
#include "uart.h"
#include "led.h"
#include "i2c_lcd.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
//	char str1[32];
	LIS_Data val;
	int ret;
	char str[32];
	SystemInit();
	LedInit(LED_RED_PIN);
	LedInit(LED_BLUE_PIN);
	LedInit(LED_GREEN_PIN);
	LedInit(LED_ORANGE_PIN);
	UartInit(9600); // initialize uart
	ret = Lcd_Init();
	UartPuts("LIS3DSH Accel Demo!\r\n");
	LIS_Init(); //initialize accel
	if(ret)
		{
			while(1)
			{

				if(LIS_IsDataAvail()) // check if new data avail
					{
						val = LIS_GetData(); // get the new data
			// print value
						sprintf(str, "X = %d, Y = %d, Z = %d", val.x, val.y, val.z);
			//Lcd_Puts(LCD_LINE1, str);
						UartPuts(str);
						Lcd_Puts(LCD_LINE1, str);
			/*ret = Lcd_Init();
						if(ret)
						{
							sprintf(str1,"X: %d Y: %d Z: %d", val.x, val.y, val.z);
							Lcd_Puts(LCD_LINE1, str1);
						}
						DelayMs(1000);
			Lcd_Puts(LCD_LINE1, str1);*/
					}
				DelayMs(1000);


		//DelayMs(1000);
		if (val.x >= 3000)
		{
			LedOn(LED_RED_PIN);
			DelayMs(1000);
			LedOff(LED_RED_PIN);
		}
		if (val.x <= -3000)
				{
					LedOn(LED_GREEN_PIN);
					DelayMs(1000);
					LedOff(LED_GREEN_PIN);
				}
		if (val.y <= -3000)
				{
					LedOn(LED_BLUE_PIN);
					DelayMs(1000);
					LedOff(LED_BLUE_PIN);
				}
		if (val.y >= 3000)
				{
				LedOn(LED_ORANGE_PIN);
				DelayMs(1000);
				LedOff(LED_ORANGE_PIN);
				}
			}
		}
	return 0;
}
